### ISSUE TITLE
ext-github_kristiank-vot/root.lexc missing

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-vot#1]
`No rule to make target 'ext-github_kristiank-vot/root.lexc', needed by 'root.lexc'.`

**Comment by snomos** [comment]
This is the wrong repo, the one with that file is https://github.com/giellalt/lang-vot-x-ext-kkankain. It seems the history of this repo has been mixed with the other one in the transfer to github.

**Comment by snomos** [comment]
See discussion in issue #2.
